language: csharp
solution: EntityFramework.LazyLoading.sln
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required
services:
  - mysql
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests.csproj