language: csharp
solution: EntityFramework.LazyLoading.sln
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required
services:
  - mysql
  - postgresql
env:
  - DB=PostgreSql CONFIGURATION=Release
  - DB=MySql CONFIGURATION=Release
install:
  - dotnet restore
before_script:
  - export Microsoft_EntityFrameworkCore_LazyLoading_Tests_DatabaseType=$DB  
script:
  - dotnet build --configuration $DB
  - (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet ef database update --configuration $DB)
  - (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet test --configuration $DB)