language: csharp
solution: EntityFramework.LazyLoading.sln
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required
services:
  - mysql
  - postgresql
env:
  global:
    - DB_NAME=ContosoUniversity
  matrix:
    - DB=PostgreSql CONFIGURATION=Release
    - DB=MySql CONFIGURATION=Release
install:
  - dotnet restore
before_script:
  - export Microsoft_EntityFrameworkCore_LazyLoading_Tests_DatabaseType=$DB 
  - sh -c "if [ '$DB' = 'MySql' ]; then (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet ef database update); fi"
script:
  - dotnet build --configuration $CONFIGURATION
  - (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet test --configuration $CONFIGURATION)