language: csharp
solution: EntityFramework.LazyLoading.sln
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required
services:
  - mysql
  - postgresql
env:
  global:
    - DB_NAME=ContosoUniversity
  matrix:
    - DB=PostgreSql CONFIGURATION=Release
    #- DB=MySql CONFIGURATION=Release
install:
  - dotnet restore
before_script:
  - export Microsoft_EntityFrameworkCore_LazyLoading_Tests_DatabaseType=$DB 
  #- sh -c "if [ '$DB' = 'MySql' ]; then mysql -e 'CREATE DATABASE \`$DB_NAME\`; USE \`$DB_NAME\`; CREATE TABLE \`__EFMigrationsHistory\` (\`MigrationId\` nvarchar(150) NOT NULL, \`ProductVersion\` nvarchar(32) NOT NULL, PRIMARY KEY (\`MigrationId\`));'; (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet ef database update); fi"
script:
  - dotnet build --configuration $CONFIGURATION
  - (cd tests/Microsoft.EntityFrameworkCore.LazyLoading.Tests && dotnet test --configuration $CONFIGURATION)